name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  PYTHONPATH: src

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.13"]

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v1
      with:
          version: "0.4.20"

    - name: Test script with `uv run`
      run: |
        uv run src/iamxed/iamxed.py --help

    - name: Install package
      run: uv pip install --system -e .[test]

    - name: Run unit tests
      run: pytest -v

    - name: Run smoke tests from installed package
      run: |
        iamxed --help